- hosts: localhost
  connection: local
  tasks:
  - include_vars: hello_vars.yaml
  - name: If variables were present
    Debug:
      msg: "The person is {{ name }} and the colour is {{ colour }}"
    when: name is defined
  - name: If variables were not present
    Debug:
      msg: "Variables were not present"
    when: name is undefined
  - name: Run the application
    shell: python app.py
    environment:
      env_var_name: "{{ name }}"
      env_var_colour: "{{ colour }}"
